### ISSUE TITLE
Feedback on moving from an old extension to a new one

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#72] opened 2023-10-12 22:46 UTC
Feel free to tell me to stop raising issues 😆 

I just wanted to describe the steps it took me to move an extension from an older schema to the new one. I think that some of those are quite important and could be documented.

- return a list of commands when there is no input
  - if a parameter is required, it won't show the command in the root list
- modify all the `{JSON} | sunbeam list --json --title "xxx"` by `[{JSON}] | {"type": "list", "title" : "xxx", "items" : .}`
  - I copied from some example which had `reload: true,` and was not understanding why filtering was failing. From what I understand now, the "legacy" filtering is still accessible with `reload: false` but `reload:true` can leverage the `.query` parameter
- modify all the actions with `push` / `open` etc... under the `onAction` key
- pass parameters to nested commands via the `params` field under `onAction` (the params are the same as defined in the commands)

And, what took me the longest to understand is that when using `command` with some `params`, the program receives `params` as STDIN, so we can do `MYVAL=$(sunbeam query -r '.params.myval')` to store a parameter in a shell variable.

What I struggled with was reading multiple parameters. I tried 
```
MYVAL=$(sunbeam query -r '.params.myval')
MYVAL2=$(sunbeam query -r '.params.myval2')
```
but it didn't work as STDIN is consumed on the first line, the solution is to do the following instead
```
PARAMS=$(sunbeam query '.params')
MYVAL=$(echo $PARAMS | sunbeam query -r '.myval')
MYVAL2=$(echo $PARAMS | sunbeam query -r '.myval2')
```

**Comment by pomdtr** [comment] 2023-10-12 23:47
Thanks for your feedback!

Good job on investigating the api the api :)

about `reload`, there are two mode for lists: 
- if reload: true, the list reload the script each time the query change. filtering is disabled, and must be handled by the script
- if reload: false, the script is run one time, and sunbeam handles the filtering

I agree that stdin is a gotcha in shell scripts (in other languages, you just load everything in one steps, using `JSON.parse`). My strategy is often to do

```
STDIN=$(cat)
MYVAL=$(echo $STDIN | sunbeam query -r '.params.myval')
MYVAL2=$(echo $STDIN | sunbeam query -r 'params.myval2')
```

You'll see that stdin is used in other places (ex: form submission).

What's your feeling on the new api so far ? I tried to keep it simple, while adding support for a lot of new features.

**Comment by pomdtr** [comment] 2023-10-12 23:48
About the migration docs, I don't think there are a lot of users so far.

I would rather focus on writing good docs for users discovering sunbeam with `v1` for now :)

**Comment by b-per** [comment] 2023-10-14 14:26
> What's your feeling on the new api so far ? I tried to keep it simple, while adding support for a lot of new features.

Does the API refer to the structure: `sunbeam command subcommand <params>`, and the fact that those parameters are checked when we execute a subcommand? 

If this is the case, yes, I think it makes things easier. It was always possible to pass data to subcommands with command attributes but I like the `params` approach more.

One thing that I am missing now (and it might be there without me knowing how to run it), is to easily input some fixed JSON and parse/display it in sunbeam. There is `sunbeam validate` and it would be great to have a `sunbeam display` (or whatever other name) to consume the JSON.

**Comment by pomdtr** [comment] 2023-10-14 15:07
Good point. Maybe sunbeam could just accept any valid page on stdin and display it.

`echo '{type: "list", "items": [...]}' | sunbeam read` ?

Of course it would not support run actions.

**Comment by b-per** [comment] 2023-10-14 17:48
What would piping it to `pbcopy` give in that case.

Taking a step back, my original request of `sunbeam display/read` is actually tied to a need for troubleshooting/debugging when writing extensions.

- with `read` I want to make sure that the JSON I generate is showing me the list/page I expect in sunbeam
- but beyond that, it would also be great to have a better way to debug issues in extensions. Most of the issues I face are about incorrectly formatted JSON. But the error I get from `sunbeam` is something like `unexpected end of JSON input` or `could not parse query: unexpected token ","`. For that case, would it be possible to at least print the whole string that sunbeam tried to parse?

**Comment by pomdtr** [comment] 2023-10-14 21:39
Yeah I struggle a bit with this too, still trying to find the best way to address this.

When your json is well formatted sunbeam but invalid sunbeam gives you an error message indicating where the issue is coming from, but when it is not able to parse the json it is not able to do so.

I like the idea to just print the the wrongly formatted string. It could also dump it into a file.

**Comment by b-per** [comment] 2023-10-15 09:39
That makes sense. What about a debug mode where all the JSON files are dumped (the incorrect and the correct ones)? This could also be used when the extension is not crashing but still not behaving as expected.

**Comment by pomdtr** [comment] 2023-10-15 14:19
Good idea, we could use an env var for this.

`SUNBEAM_DEBUG_PATH=$PWD/page.json sunbeam`

**Comment by pomdtr** [comment] 2023-10-15 14:20
btw, do you know that you can get the output of a page by just piping it to a file ?

```sunbeam github list-repos > page.json```

**Comment by b-per** [comment] 2023-10-15 17:55
I didn't know that we could pipe the output of sunbeam, no!

**Comment by pomdtr** [comment] 2023-10-15 18:08
I think the best way to address this is too add an action to the error page to preview / dump the faulty page.

I'll add the feature tomorrow.

**Comment by pomdtr** [comment] 2023-10-16 18:33
Hey @b-per, I would love to get your feedback on something.

I'm not satisifed with the current form view. I'm thinking of scrapping it for something simpler:

If you invoke a command, but a required param is missing, a form will be shown to allow you to enter it.
Same thing on the command line, if your run `sunbeam github list-prs`, a form will be shown to allow you enter the repository name.

Wtdyt about it ? Form would be less dynamic, but currently I found them far too verbose for simple cases

**Comment by b-per** [comment] 2023-10-18 09:33
I have not really looked at forms so far as I didn't really see the use case for now. I feel like having forms being automatically created depending on missing arguments for a command would make me use them much more.

**Comment by pomdtr** [comment] 2023-10-18 15:45
I removed them for now, I prefer to focus on the other views for V1. Thanks for your feedback, I have the same feeling.

**Comment by pomdtr** [comment] 2023-11-14 19:53
Closing this, as it is a bit too broad of an issue :)

**Closed by pomdtr** 2023-11-14 19:53 UTC
